// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGWsAqtqjxN1711-yqni5E-pKKbzrSP6w',
    appId: '1:59239959541:web:6dd3b742b91f52905b6ebc',
    messagingSenderId: '59239959541',
    projectId: 'impostor-cruceno',
    authDomain: 'impostor-cruceno.firebaseapp.com',
    storageBucket: 'impostor-cruceno.firebasestorage.app',
    measurementId: 'G-NWCE80CSM1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJXEbnfk4kzfroHmkNND8i0In8w8DdQ3M',
    appId: '1:59239959541:android:f37e77a4a29d6e075b6ebc',
    messagingSenderId: '59239959541',
    projectId: 'impostor-cruceno',
    storageBucket: 'impostor-cruceno.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAesWx8sMuwWbfJKDkO5h_K5eE6nBAvkKM',
    appId: '1:59239959541:ios:c6d897fbb85277535b6ebc',
    messagingSenderId: '59239959541',
    projectId: 'impostor-cruceno',
    storageBucket: 'impostor-cruceno.firebasestorage.app',
    iosBundleId: 'com.example.impostorCruceno',
  );
}
